# This file configures the execution mode of `main.py`

# one of: download (download+preprocess), reorder, plot, pr_expt
mode: reorder

# is the graph directed
directed: true 

# if applicable, which vertex orderings to compute
reorder: [parsb]

# location of graphs.db and graph files
data-dir: /home/atrostan/workspace/repos/congenial-enigma/data

# given {directed/undirected}.csv, the inclusive range of row numbers defined
# by [graph_numbers.min, graph_numbers.max] will be the graphs that will be
# downloaded/preprocessed/etc..
graph-numbers:
  min: 200
  max: 260

# if computing the vertex reordering, overwrite any existing files
overwrite: true