# This file configures the execution mode of `konect_scraper.cluster.driver`

# one of: download, preprocess, reorder, pr_expt
mode: preprocess  

# is the graph directed
directed: true 

# if applicable, which vertex orderings to compute
reorder: all

# location of graphs.db and graph directories
data-dir: /scratch/atrostan/data

# given {directed/undirected}.csv, the inclusive range of row numbers defined
# by [graph_numbers.min, graph_numbers.max] will be the graphs that will be
# downloaded/preprocessed/etc..
graph-numbers:
  min: 322
  max: 322

# if computing the vertex reordering, overwrite any existing files
overwrite: true

# sbatch parameters
time: 00-08:00:00 # DD-HH:MM:SS
mem: 187G
cpus-per-task: 48
constraint: "[skylake|cascade]"
# constraint: cascade