mode: reorder
directed: true
reorder: all
data-dir: /home/atrostan/scratch/data
graph-numbers:
  min: 297
  max: 297
overwrite: true

# sbatch parameters
time: 00-01:00:00 # DD-HH:MM:SS
mem: 187G
cpus-per-task: 48
constraint: "[skylake|cascade]"
# constraint: cascade